# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

pool: "Default"

variables:
  azureSubscription: 'Azure subscription 1'
  resourceGroupName: 'KeyVaultResourceGroup'
  location: 'EastUS'
  keyVaultName: 'TP1-KeyVault-$(Build.BuildId)'  # Utiliser un nom unique pour le KeyVault pour éviter les conflits
  secretName: 'adminPassword'

steps:
- checkout: self  # Clonage du dépôt

- task: AzureCLI@2
  displayName: 'Crée le Groupe de Ressource pour le KeyVault'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name $(resourceGroupName) --location $(location)

- task: AzureCLI@2
  displayName: 'Déployer le KeyVault'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az keyvault create --name $(keyVaultName) --resource-group $(resourceGroupName) --location $(location) --enable-rbac-authorization

# Attribuer le rôle temporaire "Key Vault Secrets User" à la connexion de service pour accéder au Key Vault
- task: AzureCLI@2
  displayName: 'Attribuer le rôle Key Vault Secrets User à la connexion de service'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $servicePrincipalObjectId = "$(AZURE_CLIENT_ID)"
      az role assignment create --role "Key Vault Secrets User" --assignee-object-id $servicePrincipalObjectId --assignee-principal-type "ServicePrincipal" --scope "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.KeyVault/vaults/$(keyVaultName)"



# Ajouter un secret dans le Key Vault
- task: AzureCLI@2
  displayName: 'Ajouter un secret dans le KeyVault'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Générer un mot de passe aléatoire pour la VM et le stocker dans le Key Vault
      $password = -join ((1..16) | ForEach-Object { (65..90) + (97..122) + (48..57) | Get-Random | % {[char]$_} })
      az keyvault secret set --vault-name $(keyVaultName) --name $(secretName) --value $password

# Retirer le rôle Key Vault Secrets User après l'ajout du secret
- task: AzureCLI@2
  displayName: 'Retirer le rôle Key Vault Secrets User de la connexion de service'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az role assignment delete --role "Key Vault Secrets User" --assignee-object-id $servicePrincipalObjectId --scope "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.KeyVault/vaults/$(keyVaultName)"

- task: AzureCLI@2
  displayName: 'Vérifier le mot de passe dans le KeyVault'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az keyvault secret show --vault-name $(keyVaultName) --name $(secretName)
